### PR TITLE
Update last name on curriculum_leads.md

### PR DESCRIPTION
**Pull request by Sierra-MC**

### CODE REVIEW

**Comment by bressler95tops** [comment]
Hi @Sierra-MC!  So recently @nasacrawford (Steve) and I did some history rewriting on this repository for clean-up purposes. Likewise, we are asking that people doing PR's with forks from before a certain time period take some additional steps before having their changes merged in.  Those steps being:

1) Delete your current fork
2) Create a new fork
3) Copy over your changes that you wanted to make to your new fork
4) Close this pull request and open a new one from your new fork

Alternatively, if you were to rebase properly, that could work but making a new fork would be much simpler. Thank you and hopefully that is not too much trouble since I see you have made a pretty simple edit for your name. 

**Some additional guidance on deleting your fork:** 

Deleting your fork: [Link here](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository)

Then you would click the fork button at the top of our repo to make a new one.

**Comment by Sierra-MC** [comment]
@bressler95tops Sorry just to be clear, this is not a fork that has been asked to be merged this is just an in-github commit add. It should not affect the commit history cleanup in any way if this is merged as is. 

Would you prefer I specifically make a fork of this repo?

**Comment by Sierra-MC** [comment]
I did sync my personal fork with this repo as well just in case.

**Comment by Sierra-MC** [comment]
If that does cover what you were concerned about, rather than having people delete their forks fully in the future syncing them (see sync fork button in capture below) may be an easier and more seamless process.

image

**Comment by bressler95tops** [comment]
Thanks for the questions @Sierra-MC while this would be generally true for an in-github commit, the way those works, is they still makes the pull request using a fork from your account.  If you look at the top of this page, there is a link referencing this branch on your fork: [https://github.com/Sierra-MC/Transform-to-Open-Science/tree/patch-2](https://github.com/Sierra-MC/Transform-to-Open-Science/tree/patch-2)

We are just asking people with older forks do this for safety since that cleaned up commit history could make it's way back in despite keeping the fork up to date.  Once you do have that done, then you are good to keep making changes as usual and keep your fork up to date as you suggested since that is good practice.

**Comment by Sierra-MC** [comment]
I believe I have  successfully rebased and am now showing the same number of commits on my fork's history as the main repos.

**Comment by bressler95tops** [comment]
To give a little more context to what was done, and why we are taking this approach: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#fully-removing-the-data-from-github

Even though it may be showing as 1 commit being merged, it may still create a mix and match of old and new commit ID's

Hope this information is helpful

**Comment by Sierra-MC** [comment]
image
^ Confirming the rebase command does show this history is up to date with the upstream (NASA/Transform-to-Open-Science:main) branch (created as a separate remote from my fork which is `origin`).

Additionally confirming the number of commits in the commit history of the requested merge is consistent with the   number of commits/commit history of the main branch here +1:
image

image

**Comment by bressler95tops** [comment]
@Sierra-MC okay actually this seems solid to me using the rebase command, we are just careful about asking most people to do this since they may not know how to do so thus why we just ask to recreate the fork.  If I may ask you to:

git push origin patch-2--force

Just to make sure any changes from the rebase command make it's way onto that branch then I can go ahead and merge it in

**Comment by Sierra-MC** [comment]
image
Confirming that everything is up to date using that command.

**Comment by bressler95tops** [comment]
@Sierra-MC thank you, apologies if this caused an inconvenience, we are just trying to make sure those deleted commits do not find their way back onto the repository, I have merged your change in

**Comment by Sierra-MC** [comment]
No problem at all @bressler95tops. I do hope it came through that the `sync fork` button is what did all the rebasing. I just used the `rebase` and `push  --force` options to fully confirm/convince you/myself of that. But they did already, on the first use, have those up to date messages I  pasted above. It might just make it easier as you were mentioning others have trouble with the `git` commands like `rebase`, the github `sync fork` UI does a rebase rather than a merge. Having users confirm the number of commits/commit history like I did here with screenshots may also help give you/Steve piece of mind to make sure you're not cluttering up your commit history here, and allows people to keep the contribution history they have by holding onto their old forks and syncing them with the one button.

Thanks for merging! I appreciate the name update!

**Pull request merged**
