### PR TITLE
Fix typo in OS101 M5 L4.3 How to Share

### PR DESCRIPTION
**Pull request by 4N0NYM0U5MY7H**
Changed "peer print" to "pre-print" under the Potential Disadvantages section of Pros and Cons of Preprints.

### CODE REVIEW

**Comment by bressler95tops** [comment]
Thanks @4N0NYM0U5MY7H I will add your suggestion for review and will update you on the result of that

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for reviewing the change. Please update. I will also notify the MOOC developers and update the change on the ILT slides.

**Comment by katblanchette** [comment]
@bressler95tops - The MOOC and ILT slides have been updated. Please close this issue when you are finished.

**Comment by bressler95tops** [comment]
@katblanchette yes looks good to me. Feel free to review the 'files changed' tab above if you want to give things a double check as well, or have the MOOC developers do so, so they can get a more precise view of what changed. I have gone ahead and merged the changes on my end. Let me know when you have had a chance to work this into the MOOC as well so we can officially check this off.

**Comment by bressler95tops** [comment]
@4N0NYM0U5MY7H Thank you for your patience. This item is now completed on the self guided version of OS101 and the appropriate status label will be removed for tracking purposes in order to mark it as "Complete".

**Pull request merged**
