### PR TITLE
Update F8 and F16 in funding_opportunities.md

### PR DESCRIPTION
**Pull request by paigem**
Update F.8 and F.16 summaries per the amendments from 20 October 2023

### CODE REVIEW

**Comment by paigem** [comment]
Tagging @RPaseka for review

**Comment by RPaseka** [comment]
This looks good to me -- thanks for the update @paigem

**Comment by bressler95tops** [comment]
Hi @paigem. So recently @nasacrawford (Steve) and I did some history rewriting on this repository for clean up purposes. Your fork may be okay but just as a precaution we are asking that people with forks from before a certain time period do the following:

1) Delete your current fork
2) Create a new one
3) Copy over your changes that you wanted to make to your new fork
4) Close this pull request and open a new one from your new fork

Alternatively, if you were to rebase properly, that could work but making a new fork would be much simpler. Thanks, hope it's not too much trouble for you since it looks like you had modified just one file.

**Comment by bressler95tops** [comment]
I know you are pretty familiar with these things but in case it is helpful:

Deleting your fork: [Link here](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository)

Then you would click the fork button at the top of our repo to make a new one.

**Pull request closed without merging**
