### PR TITLE
Fix a typo in Module 2 Lesson 3.

### PR DESCRIPTION
**Pull request by TomLav**

### CODE REVIEW

**Comment by bressler95tops** [comment]
@TomLav change makes sense to me, thanks for the contribution!  I will run this by the curriculum development team

**Comment by bressler95tops** [comment]
Merging into development version for now since this is a straight forward change, will report when this change has made its way to the curriculum.

**Comment by katblanchette** [comment]
@bressler95tops - Please move forward with the fix. Thanks!

**Comment by bressler95tops** [comment]
Even though @TomLav posted this some time back, it resolves the same problem as #713 so we can go ahead and close this one out.

**Comment by katblanchette** [comment]
@bressler95tops Copy and thank you!

**Pull request merged**
