### PR TITLE
typos

### PR DESCRIPTION
**Pull request by lauracion**
Addresses a few minor typos

### CODE REVIEW

**Comment by bressler95tops** [comment]
Thank you Laura, I will queue this for the review process that we will be working on in the coming weeks, thanks for diligently making suggestions for the curriculum!

**Comment by katblanchette** [comment]
@bressler95tops - Hi Brian - I am not sure which typos to correct. If you know what they are, please correct. Thanks!

**Comment by bressler95tops** [comment]
@katblanchette I have reviewed this and it looks good to me. Feel free to review the 'files changed' tab above if you want to give things a double check as well, or have the MOOC developers do so, so they can get a more precise view of what changed. I will go ahead and merge the changes since all of these are spelling / semantic / grammar changes. Let me know when you have had a chance to work this into the MOOC as well so we can officially check this off.

Also worth noting that I cleared a merge conflict, that can happen when the file gets modified by many people in the same time period.

**Comment by bressler95tops** [comment]
@lauracion thank you for patience on this, we are in the process of reviewing contributions and we welcome any fixes you may come across

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for updating the content. I have shared this information with the MOOC developers and will notify you when the change is made.

**Comment by bressler95tops** [comment]
@lauracion @katblanchette thank you for your patience, this change has been corrected on both the MOOC and the GitHub version of the curriculum and the curriculum status label can now be removed.

**Pull request merged**
