### PR TITLE
Module 4 Changes Ready

### PR DESCRIPTION
**Pull request by bressler95tops**
Changes per ARC curriculum team.

### CODE REVIEW

**Comment by PaigeDAO** [comment]
Nature is cited here. Don't they generally put their articles behind a paywall?

**Comment by cgentemann** [comment]
Nature does both subscription only and open access. We should definitely only cite open resources including open-access papers. @bressler1995

**Comment by bressler95tops** [comment]
Thank you for the input on this @cgentemann, I hope that clarifies things with regards to Nature being cited on this module @PaigeDAO, feel free to let us know if you have any other concerns.

**Comment by PaigeDAO** [comment]
Thank you both @cgentemann and @bressler1995 .  As a builder, these are some thoughts I'm working through re: open source.  Sharing here in case there is more interest in pursuing the conversation.  On [MIRROR](https://mirror.xyz/frontierdao.eth/PlIDpXDi4xDpfTy-5OvUab3D9pjKtGgUnDSQyEGs4wQ)

**Pull request merged**
