### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by bryce-wedig**
Cleaned up typos across all five Modules, including:
- style of certain proper nouns (e.g., "GitHub" instead of "Github")
- using American English instead of British English
- ligatures
- and others

This PR addresses #656 (and maybe closes it, as specific typos aren't called out there) and fixes:
- #638 
- #601 
- #603

### CODE REVIEW

**Comment by bressler95tops** [comment]
Thank you for having a look at this @bryce-wedig.  Like I mentioned at the symposium, we are looking at procedures for contribution review so stay tuned and we will get your changes pushed through hopefully within the next few weeks!

**Comment by katblanchette** [comment]
@bressler95tops - Please correct.

**Comment by bressler95tops** [comment]
@katblanchette I reviewed this and made a minor correction.  Feel free to review the 'files changed' tab above if you want to give things a double check as well, or have the MOOC developers do so, so they can get a more precise view of what changed.  I will go ahead and merge the change.

**Comment by bressler95tops** [comment]
On another note, thank you @bryce-wedig for identifying the potential duplicates, I will review these as well.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you! I see that there 27 updates within the File Changed tab and have added these to the MOOC Developers list to update. I will notify you when they are complete.

**Comment by bressler95tops** [comment]
@bryce-wedig thank you for your patience.  I have looked this item over on the MOOC and it does appear to be done there so we can officially mark this as complete by removing the appropriate status label.

**Pull request merged**
