### PR TITLE
Minor typo in readme.md

### PR DESCRIPTION
**Pull request by NPalopoli**
Corrected sentence that should end in '.' instead of '?'

### CODE REVIEW

**Comment by bressler95tops** [comment]
Thank you @NPalopoli, I will add this (and your other pull requests) to our review process.  I expect initial review to occur at the end of this month and monthly thereafter.  Stay tuned, as we get to your contribution.  We greatly appreciate it and feel free to continue submitting suggestions.

**Comment by katblanchette** [comment]
@bressler95tops - Please correct. We will email update to MOOC Developer.

**Comment by bressler95tops** [comment]
Thank you for your patience on this @NPalopoli we are little by little reviewing everyone's suggestions.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you! I have shared this with the MOOC developers and will connect with you when it is updated.

**Comment by bressler95tops** [comment]
@NPalopoli thank you for your patience this item is now completed on the self guided version of OS101 and the appropriate status label will be removed for tracking purposes in order to mark it as "Complete".

**Pull request merged**
