### PR TITLE
Typo in M2-L3 readme.md

### PR DESCRIPTION
**Pull request by NPalopoli**
Changed 'or' to 'on' in the phrase 'get you started on creating'

### CODE REVIEW

**Comment by bressler95tops** [comment]
@katblanchette this one makes sense to me after looking at the 'files changed' tab.  I can get this one merged if you concur

**Comment by katblanchette** [comment]
@bressler95tops - I concur. Please update. Thank you!

**Comment by bressler95tops** [comment]
@katblanchette Sounds good I went ahead and got that merged in. Feel free to review the 'files changed' tab above if you want to give things a double check as well, or have the MOOC developers do so, so they can get a more precise view of what changed. Let me know when you have had a chance to work this into the MOOC as well so we can officially check this off.

**Comment by bressler95tops** [comment]
@katblanchette keeping this item as still pending on the MOOC.  It may have slipped out of the V1 tracking sheet and the OS101 developers may not have seen it.

**Pull request merged**
