### PR TITLE
Missing period in readme.md

### PR DESCRIPTION
**Pull request by NPalopoli**
Added missing period

### CODE REVIEW

**Comment by katblanchette** [comment]
@bressler95tops - Please update.

**Comment by bressler95tops** [comment]
@katblanchette I have reviewed this and it looks good to me. Feel free to review the 'files changed' tab above if you want to give things a double check as well, or have the MOOC developers do so, so they can get a more precise view of what changed. I will go ahead and merge the changes since all of these are spelling / semantic / grammar changes. Let me know when you have had a chance to work this into the MOOC as well so we can officially check this off.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for updating the content. I have shared this information with the MOOC developers and will notify you when the change is made.

**Comment by bressler95tops** [comment]
@NPalopoli thank you for your patience this item is now completed on the self guided version of OS101 and the appropriate status label will be removed for tracking purposes in order to mark it as "Complete".

**Pull request merged**
