### PR TITLE
typos

### PR DESCRIPTION
**Pull request by lauracion**
Addresses a few minor typos

### CODE REVIEW

**Comment by bryce-wedig** [comment]
This fixes #602

**Comment by katblanchette** [comment]
@bressler95tops - Please correct.

**Comment by bressler95tops** [comment]
@katblanchette I have reviewed this and it looks good to me. Feel free to review the 'files changed' tab above if you want to give things a double check as well, or have the MOOC developers do so, so they can get a more precise view of what changed. I will go ahead and merge the change since all of these are spelling / semantic / grammar changes.

**Comment by bressler95tops** [comment]
thank you @lauracion for you patience while we figured out our review process and @bryce-wedig for taking the time to find the duplicate change

**Comment by katblanchette** [comment]
Thank you @bressler95tops!

**Comment by bressler95tops** [comment]
No problem @katblanchette I was just about to ask about the links above but I see you have removed them, I am assuming this was meant for another Issue/PR?

**Comment by katblanchette** [comment]
@bressler95tops, correct, the links were for another issue.

**Comment by bressler95tops** [comment]
@katblanchette added #896 for the edit that you mentioned

**Comment by bressler95tops** [comment]
@lauracion @katblanchette thank you for your patience, this PR is implemented on the MOOC and on GitHub.  The only small detail to note is #693 overrides the definition of portability as a whole new definition.  Otherwise, your suggestions still hold true.  Thank you for your feedback!

**Pull request merged**
